# POLIFONIA prefixes
PREFIX core:    <https://w3id.org/polifonia/ON/core/> 
PREFIX mp:      <https://w3id.org/polifonia/ON/musical-performance/>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pr:      <https://w3id.org/polifonia/resource/>

# SPARQL anything prefixes
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>

SELECT DISTINCT
    ?recordingID
WHERE {

    SERVICE <x-sparql-anything:> {

        # location for json preprocessed file
		fx:properties fx:location "data/places_v3_aligned_ids.json"  ;
	  	fx:media-type "application/json" ;
		fx:blank-nodes false    .


        { SELECT DISTINCT ?recordingID (COUNT(?artistID) as ?artist_count ) WHERE {

            # Recordings with artists
            ?recording  xyz:track%5Fid ?recordingID ;
                    xyz:artists ?artistList .
                    # artist
                    ?artistList ?li ?artist .
                    ?artist xyz:name%5Firi ?artistID .
                    
        } GROUP BY ?recordingID }

### Uncomment one of the filter to select songs just with 1,2 or 3 artists

#        FILTER (?artist_count = 1)
#        FILTER (?artist_count = 2)
        FILTER (?artist_count = 3)


	}
} 
