# SPARQL anything prefixes
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>


SELECT DISTINCT ?sym ?score
WHERE {

    SERVICE <x-sparql-anything:> {

        fx:properties fx:location "data/harm_sym.json"  ;
        fx:media-type "application/json" ;
        fx:blank-nodes false    .

        {   SELECT DISTINCT ?sym WHERE {
                ?file xyz:har%5Fsim%5Fpairs ?symList .
    
                ?symList ?li ?sym .
            }
        }

    } .

}
