# Query to extract data from preprocessed file with line lyric similarity related to Music domain
# and build a Knowledge Graph according to Polifonia ontology network, using sparql.anything
#
# Raw file:
# 
# Polifonia KG ontology: https://github.com/polifonia-project/sonar2021_demo/issues/14


# POLIFONIA prefixes
PREFIX core:    <https://w3id.org/polifonia/ON/core/> 
PREFIX mp:      <https://w3id.org/polifonia/ON/musical-performance/>
PREFIX mc:      <https://w3id.org/polifonia/ON/musical-composition/>
PREFIX mf:      <https://w3id.org/polifonia/ON/musical-feature/>
PREFIX cm:      <https://w3id.org/polifonia/ON/comparative-measure/>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pr:      <https://w3id.org/polifonia/resource/>

# SPARQL anything prefixes
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>


SELECT 

(COUNT(?lyrSim) as ?count)

WHERE {

    SERVICE <x-sparql-anything:> {

        fx:properties fx:location "data/lyr_sim_v1.json"  ;
        fx:media-type "application/json" ;
        fx:blank-nodes false    .

        {   SELECT DISTINCT ?lyrSim WHERE {

            ?lyrSim xyz:lyrSimId ?lyrSimId .
#                        xyz:compSimScore ?compSimScore ;
#                        xyz:humanSimScore ?humanSimScore ;
#                        xyz:lineA ?lineAobject ;
#                        xyz:lineB ?lineBobject .

#            ?lineAobject xyz:lineLabel ?lineALabel ;
#                    xyz:recordingId ?recordingAId ;
#                    xyz:lineNumber ?lineNumberA .

#            ?lineBobject xyz:lineLabel ?lineBLabel ;
#                    xyz:recordingId ?recordingBId ;
#                    xyz:lineNumber ?lineNumberB .


            }
        }
            
        } 

}